---
- hosts: 192.168.196.129
  tasks:
    - name: install packages
      become: true
      become_user: root
      dnf:
        state: present
        name:
         - epel-release
         -figlet
         
